export const BIKE_ATTEPT = 'BIKE_ATTEPT';

export const BIKE_SUCCESS = 'BIKE_SUCCESS';

export const BIKE_FAILED = 'BIKE_FAILED'


export const VEHIECLE_TYPE_ATTEPT = "VEHIECLE_TYPE_ATTEPT";
export const VEHIECLE_TYPE_SUCESS = "VEHIECLE_TYPE_SUCESS";
export const VEHIECLE_TYPE_FAILED = "VEHIECLE_TYPE_FAILED";

export const COLOR_ATTEPT = "COLOR_ATTEPT";
export const COLOR_SUCCESS = "COLOR_SUCCESS"; 
export const COLOR_FAILED = "COLOR_FALIED";

export  const ITS_OWN_SUCCESS = "ITS_OWN_SUCCESS";
export const ITS_OWN_FAILED = "ITS_OWN_SUCCESS";
export const IT_OWN_ATTEPT = "IT_OWN_ATTEPT";