
export const SIGNUP_ATTEPT = 'SIGNUP_ATTEPT';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SIGNUP_FAILED = 'SIGNUP_FAILED'


export const LOGOUT_ATTEPT =  'LOGOUT_ATTEPT'

export const FACEBOOK_LOGOUT_ATTEPT = 'FACEBOOK_LOGOUT_ATTEPT';

export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN'